In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("heart.csv")
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [4]:
data.isna().sum

<bound method DataFrame.sum of         age    sex     cp  trestbps   chol    fbs  restecg  thalach  exang  \
0     False  False  False     False  False  False    False    False  False
1     False  False  False     False  False  False    False    False  False
2     False  False  False     False  False  False    False    False  False
3     False  False  False     False  False  False    False    False  False
4     False  False  False     False  False  False    False    False  False
...     ...    ...    ...       ...    ...    ...      ...      ...    ...
1020  False  False  False     False  False  False    False    False  False
1021  False  False  False     False  False  False    False    False  False
1022  False  False  False     False  False  False    False    False  False
1023  False  False  False     False  False  False    False    False  False
1024  False  False  False     False  False  False    False    False  False

      oldpeak  slope     ca   thal  target
0       False  False  False  False   False
1       False  False  False  False   False
2       False  False  False  False   False
3       False  False  False  False   False
4       False  False  False  False   False
...       ...    ...    ...    ...     ...
1020    False  False  False  False   False
1021    False  False  False  False   False
1022    False  False  False  False   False
1023    False  False  False  False   False
1024    False  False  False  False   False

[1025 rows x 14 columns]>

In [5]:
data = data.rename(columns={
    'age': 'age',
    'sex': 'sex',
    'cp': 'chest_pain_type',
    'trestbps': 'resting_bp',
    'chol': 'cholesterol',
    'fbs': 'fasting_blood_sugar',
    'restecg': 'rest_ecg',
    'thalach': 'max_heart_rate',
    'exang': 'exercise_induced_angina',
    'oldpeak': 'st_depression',
    'slope': 'st_slope',
    'ca': 'num_major_vessels',
    'thal': 'thalassemia',
    'target': 'target'
})
data

,age,sex,chest_pain_type,resting_bp,cholesterol,fasting_blood_sugar,rest_ecg,max_heart_rate,exercise_induced_angina,st_depression,st_slope,num_major_vessels,thalassemia,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [6]:
# scalling and encoding the categorical and numerical collumn

In [7]:
num_cols=['age','resting_bp','cholesterol','max_heart_rate','st_depression']
cat_cols = ['sex', 'chest_pain_type', 'fasting_blood_sugar',
            'rest_ecg', 'exercise_induced_angina',
            'st_slope', 'num_major_vessels', 'thalassemia']

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

#  for transformation encoding scaling missing values

In [ ]:
num_pipeline=Pipeline([('imputer',SimpleImputer(strategy='median')),
('scaler',StandardScaler())
])
#  to standardize the values and to fill missing values

In [10]:
cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

In [11]:
preprocess=ColumnTransformer([

('nums',num_pipeline,num_cols),
('categ',cat_pipeline,cat_cols)
])

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [13]:
#  comparison of the pipelines build

In [14]:
pipe_lr = Pipeline([
    ('prep', preprocess),
    ('model', LogisticRegression(max_iter=1000))
])

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

pipe_rf = Pipeline([
    ('prep', preprocess),
    ('model', RandomForestClassifier())
])

In [16]:
x=data.drop('target',axis=1)
y=data['target']

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
pipe_lr.fit(x_train, y_train)
pipe_rf.fit(x_train, y_train)

AttributeError: 'numpy.ndarray' object has no attribute 'fit'

In [ ]:
print("preprocess:", type(preprocess))
print("X_train:", type(x_train))
print("pipe_rf:", pipe_rf)